//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioModelo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public int IdUnidad { get; set; }
        public int IdConsorcio { get; set; }
        public string Nombre { get; set; }
        public string NombrePropietario { get; set; }
        public string ApellidoPropietario { get; set; }
        public string EmailPropietario { get; set; }
        public Nullable<int> Superficie { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdUsuarioCreador { get; set; }
    
        public virtual Consorcio Consorcio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
